### ISSUE TITLE
Tail should return the rest of the list

### ISSUE THREAD

**Issue by leonderijke** [at-import/SassyLists#25]
Currently, `tail` is an alias of `last`, returning the last item in the list. It is a common idiom to split a list into a head (first item) and tail (rest of the list), especially when using recursion.

Therefore, I propose `tail` or `rest` to return the rest of the list instead of the last item.

Example usage (based on this gist: https://gist.github.com/jlong/8760275):

``` scss
//
// map-fetch($map, $keys)
//
// An easy way to fetch a deep value in a multi-level map. Works much like
// map-get() except that you pass multiple keys as the second parameter to
// go down multiple levels in the nested map.
//
@function map-fetch($map, $keys) {
  $value: map-get($map, head($keys));
  @if (length($keys) > 1) {
    @return map-fetch($value, tail($keys));
  } @else {
    @return $value;
  }
}
```

The code could be as easy as:

``` scss
@function tail($list) {
  @return slice($list, 2);
}
```

I'd be happy to submit a pull request, if needed.
