### ISSUE TITLE
Support reduction

### ISSUE THREAD

**Issue by thertweck** [at-import/SassyLists#48]
Hello!

A sl-reduce() function would be great! Check this:

``` scss
@function reduce($list, $callback, $accumulator: 0){
    @if(not function-exists($callback)){
        @warn "Cannot find callback '" + inspect($callback) + "'.";
        @return $accumulator;
    }@else{
        @each $item in $list {
            $accumulator: call($callback, $accumulator, $item);
        }
        @return $accumulator;
    }
}
```

And a callback:

``` scss
@function add($a, $b){
    @return $a + $b;
}
```

Could be used like this:

``` scss
@debug reduce((1 2 3), add); // yields 6
@debug reduce(("hello" "world"), add, ""); // yields "hello world"
```
